trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.102
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@0
  displayName: 'Installing NuGet Tools...'
  inputs:
    versionSpec: '4.9.2'

- script: dotnet build --configuration $(buildConfiguration) src/Blazored.Typeahead/Blazored.Typeahead.csproj
  displayName: 'Building $(buildConfiguration)...'

- task: DotNetCoreCLI@2
  displayName: 'Generating NuGet Package... '
  inputs:
    command: pack

    arguments: --no-build
    packagesToPack: src/Blazored.Typeahead/Blazored.Typeahead.csproj
    configuration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
